ci: bump actions/checkout to v7 (latest)
Trying to fix the integration test CI issue:

```
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-***9-deprecation-of-node-20-on-github-actions-runners/
Run actions/checkout@v4
Syncing repository: infinilabs/framework-enterprise-plugins
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/f***94cdca-64a7-480f-a850-cfb33343e***88' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/coco-server/coco-server/framework-enterprise-plugin
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Determining the default branch
  Retrieving the default branch name
  Bad credentials - https://docs.github.com/rest
  Waiting ***7 seconds before trying again
  Retrieving the default branch name
  Bad credentials - https://docs.github.com/rest
  Waiting ***5 seconds before trying again
  Retrieving the default branch name
  Error: Bad credentials - https://docs.github.com/rest
```

I don't think bumping this really help, but maybe i am fighting with a bug that
has already been fixed.

Update: this commit didn't resolve the issue, generating a new PAT did.
But it still makes sense to keep this commit.